apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-detection
  name: object-detection-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: object-detection
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
  labels:
    app: object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: ashrafsaleem/fit5225:latest
        ports:
        - containerPort: 80
