apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
  labels:
    app: object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: ashrafsaleem/fit5225:latest
        ports:
        - containerPort: 80
