apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      cpu: 0.5
    defaultRequest:
      cpu: 0.3
    type: Container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-detection
  name: object-detection-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: object-detection
  type: NodePort
  externalIPs:
  - 118.138.245.59

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
  labels:
    app: object-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: ashrafsaleem/fit5225:latest
        ports:
        - containerPort: 80
